// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import ()

type Match struct {
	ID       string `json:"id"`
	Hometeam string `json:"hometeam"`
	Awayteam string `json:"awayteam"`
	Datetime string `json:"datetime"`
	Stadium  string `json:"stadium"`
	Status   string `json:"status"`
}
